version: '3'
services:
  mongodb:
    container_name: product-service-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - product-service-network

networks:
  product-service-network:
